[package]
name = "rotor"
description = """
    The mio-based framework for doing I/O in simple and composable way
"""
license = "MIT"
readme = "README.rst"
keywords = ["io", "loop", "state", "machine", "mio"]
homepage = "http://github.com/tailhook/rotor"
version = "0.3.0"
authors = ["paul@colomiets.name"]

[dependencies]
#mio = "0.4.3"
log = "0.3.2"
netbuf = "0.2"
memchr = "0.1.6"
time = "0.1.23"

[lib]
name = "rotor"
path = "src/lib.rs"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
rev = "ac165e0"
